server:
  port: 8085

api:
  security:
    token:
       secret: 'c8d1e3f7g9h2j4k6l8m0n5p9q7r5s3t1u0v8w6x4y2z0a1b3c5d7e9f'

spring:
  application:
    name: "gateway"
  cloud:
    gateway:
      server:
        webflux:
          globalcors:
            add-to-simple-url-handler-mapping: true
            cors-configurations:
              '[/**]':
                allowedOrigins: "http://localhost:4200"
                allowedMethods: "*"
                allowedHeaders: "*"
                allowCredentials: true
          # ───────────────────────────────
          # ENTITY SERVICE (MEDIC)
          # ───────────────────────────────
          routes:
            - id: ms-perfil-medic
              uri: http://localhost:8082
              predicates:
                # Captura /{tenant}/medic e o que vier depois
                - Path=/{tenant}/medic/**
              filters:
                # O RewritePath remove o UUID da URL para o microservice não dar 404
                - RewritePath=/(?<tenant>.*)/medic/(?<remaining>.*), /medic/${remaining}
              #   - name: CircuitBreaker
              #     args:
              #       name: entityServiceCircuit
              #       fallbackUri: forward:/fallback/entity

            # ───────────────────────────────
            # ENTITY SERVICE (PATIENT)
            # ───────────────────────────────
            - id: ms-perfil-patient
              uri: http://localhost:8082
              predicates:
                # Captura /{tenant}/patient e o que vier depois
                - Path=/{tenant}/patient/**
              filters:
                - RewritePath=/(?<tenant>.*)/patient/(?<remaining>.*), /patient/${remaining}
#                - name: CircuitBreaker
#                  args:
#                    name: entityServiceCircuit
#                    fallbackUri: forward:/fallback/entity
            # ───────────────────────────────
            # ENTITY SERVICE (ASSISTANT)
            # ───────────────────────────────
            - id: ms-perfil-assistant
              uri: http://localhost:8082
              predicates:
                # Captura /{tenant}/assistant e o que vier depois
                - Path=/{tenant}/assistant/**
              filters:
                - RewritePath=/(?<tenant>.*)/assistant/(?<remaining>.*), /assistant/${remaining}
#                - name: CircuitBreaker
#                  args:
#                    name: entityServiceCircuit
#                    fallbackUri: forward:/fallback/entity

            # ───────────────────────────────
            # ENTITY SERVICE (PERSON)
            # ───────────────────────────────
            - id: ms-perfil-person
              uri: http://localhost:8082
              predicates:
                # Captura /{tenant}/person e o que vier depois
                - Path=/{tenant}/person/**
              filters:
                - RewritePath=/(?<tenant>.*)/person/(?<remaining>.*), /person/${remaining}
#                - name: CircuitBreaker
#                  args:
#                    name: entityServiceCircuit
#                    fallbackUri: forward:/fallback/entity

            # ───────────────────────────────
            # APPOINTMENT SERVICE (SCHEDULE)
            # ───────────────────────────────
            - id: ms-appointment-schedule
              uri: http://localhost:8084
              predicates:
                # Captura /{tenant}/schedule e o que vier depois
                - Path=/{tenant}/schedule/**
              filters:
                - RewritePath=/(?<tenant>.*)/schedule/(?<remaining>.*), /schedule/${remaining}
#                - name: CircuitBreaker
#                  args:
#                    name: appointmentServiceCircuit
#                    fallbackUri: forward:/fallback/appointments

            # ───────────────────────────────
            # APPOINTMENT SERVICE (APPOINTMENT)
            # ───────────────────────────────
            - id: ms-appointment-appointments
              uri: http://localhost:8084
              predicates:
                # Captura /{tenant}/appointment e o que vier depois
                - Path=/{tenant}/appointment/**
              filters:
                - RewritePath=/(?<tenant>.*)/appointment/(?<remaining>.*), /appointment/${remaining}
#                - name: CircuitBreaker
#                  args:
#                    name: appointmentServiceCircuit
#                    fallbackUri: forward:/fallback/appointments

            # ───────────────────────────────
            # AUTH SERVICE (AUTH)
            # ───────────────────────────────
            - id: ms-user-auth
              uri: http://localhost:8081
              predicates:
                Path=/auth/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: userServiceCircuit
                    fallbackUri: forward:/fallback/auth c
            # ───────────────────────────────
            # AUTH SERVICE (COMPANY)
            # ───────────────────────────────
            - id: ms-company-auth
              uri: http://localhost:8081
              predicates:
                Path=/company/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: userServiceCircuit
                    fallbackUri: forward:/fallback/auth
logging:
  level:
    org:
      springframework:
        cloud:
          gateway: DEBUG
        security: DEBUG
